# Generated by Django 3.2.4 on 2021-08-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
