# Generated by Django 3.2.4 on 2021-08-08 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0003_auto_20210808_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogging',
            name='author',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='blogging',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img/blog/'),
            preserve_default=False,
        ),
    ]
