# Generated by Django 3.2.4 on 2021-08-12 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0009_auto_20210809_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['agency'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=30)),
                ('imageLogo', models.ImageField(upload_to='static/img/job/')),
                ('jobLocation', models.CharField(max_length=30)),
                ('estimatedSalary', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('timeAdded', models.TimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyName', to='kck2021.department')),
            ],
            options={
                'ordering': ['jobName'],
            },
        ),
    ]
