# Generated by Django 3.2.4 on 2021-08-12 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0010_auto_20210812_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='estimatedSalary',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='career',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
