# Generated by Django 3.2.4 on 2021-08-12 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0011_auto_20210812_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='career',
            name='timeAdded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
