# Generated by Django 3.2.4 on 2021-08-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0013_job_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='jobType',
        ),
        migrations.AddField(
            model_name='project',
            name='jobType',
            field=models.ManyToManyField(related_name='job_spec', to='kck2021.Job'),
        ),
    ]
