# Generated by Django 3.2.4 on 2021-08-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0015_project_introimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='intro',
            new_name='projectIntro',
        ),
    ]
