# Generated by Django 3.2.4 on 2021-08-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0016_rename_intro_project_projectintro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='introImage',
        ),
    ]
