# Generated by Django 3.2.4 on 2021-08-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0017_remove_project_introimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='fifthImage8x7',
            new_name='fifthImage',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='firstImage8x7',
            new_name='firstImage',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='fourImage8x7',
            new_name='fourthImage',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='secondImage8x7',
            new_name='secondImage',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sixthImage8x7',
            new_name='sixthImage',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='thirImage8x7',
            new_name='thirdImage',
        ),
    ]
