# Generated by Django 3.2.4 on 2021-08-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0023_project_openingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fifthImage',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='firstImage',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fourthImage',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='openingImage',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='secondImage',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sixthImage',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thirdImage',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
