# Generated by Django 3.2.4 on 2021-08-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0024_auto_20210825_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
