# Generated by Django 3.2.4 on 2021-08-24 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0025_alter_career_timeadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='timeAdded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
