# Generated by Django 3.2.4 on 2021-08-25 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0027_alter_career_timeadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='timeAdded',
        ),
        migrations.AddField(
            model_name='career',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
