# Generated by Django 3.2.4 on 2021-08-25 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0029_alter_career_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='time',
        ),
        migrations.AddField(
            model_name='career',
            name='timeAdded',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
