# Generated by Django 3.2.4 on 2021-08-25 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0030_auto_20210825_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='timeAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
