# Generated by Django 3.2.4 on 2021-08-25 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0034_alter_career_timeadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='timeAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 14, 26, 38, 358647, tzinfo=utc)),
        ),
    ]
