# Generated by Django 3.2.4 on 2021-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0037_alter_career_timeadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
