# Generated by Django 3.2.4 on 2022-10-16 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0045_rename_projectimages_project_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='timeAdded',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
