# Generated by Django 4.2 on 2023-05-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0046_alter_career_timeadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fifthImage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='firstImage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='fourthImage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='secondImage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sixthImage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thirdImage',
        ),
        migrations.AlterField(
            model_name='project',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kck2021.projectimages'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='media/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kck2021.project')),
            ],
        ),
    ]
