# Generated by Django 4.2 on 2023-05-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0047_remove_project_fifthimage_remove_project_firstimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='kck2021.project'),
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
