# Generated by Django 4.2 on 2023-05-23 13:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0049_alter_article_body_alter_project_projectintro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectIntro',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
