# Generated by Django 4.2 on 2023-07-02 08:59

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0051_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='day',
        ),
        migrations.RemoveField(
            model_name='article',
            name='month',
        ),
        migrations.RemoveField(
            model_name='project',
            name='openingImage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectIntro',
        ),
        migrations.RemoveField(
            model_name='project',
            name='value',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 8, 58, 58, 71856, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2023, 7, 2, 8, 59, 16, 402, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='KCK', max_length=255),
        ),
    ]
