# Generated by Django 4.2 on 2023-07-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0052_remove_article_day_remove_article_month_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImage',
            new_name='ProjectImages',
        ),
        migrations.RenameField(
            model_name='projectimages',
            old_name='images',
            new_name='image',
        ),
    ]
