# Generated by Django 4.2 on 2023-12-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0055_jobtype_delete_text_career_jobtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='estimatedSalary',
        ),
        migrations.AddField(
            model_name='career',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
