# Generated by Django 4.2 on 2023-12-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0056_remove_career_estimatedsalary_career_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='imageLogo',
        ),
    ]
