# Generated by Django 4.2 on 2023-12-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0058_company_legalcategory_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='kck2021.company'),
        ),
    ]
