# Generated by Django 4.2 on 2023-12-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0060_alter_legal_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'verbose_name_plural': 'Legal Terms'},
        ),
    ]
