# Generated by Django 4.2 on 2024-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0062_alter_legal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('front', models.ImageField(upload_to='identity/')),
                ('back', models.ImageField(upload_to='identity/')),
                ('selfie', models.ImageField(upload_to='identity/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecategories',
            options={'ordering': ['category'], 'verbose_name_plural': 'Articles - Categories'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['jobName'], 'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Legal - Companies'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['agency'], 'verbose_name_plural': 'Careers - Departments'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['specialization'], 'verbose_name_plural': 'Projects - Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name_plural': 'Careers - Job Type'},
        ),
        migrations.AlterModelOptions(
            name='legal',
            options={'verbose_name_plural': 'Legal - Terms'},
        ),
        migrations.AlterModelOptions(
            name='legalcategory',
            options={'ordering': ['category'], 'verbose_name_plural': 'Legal - Categories'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['dateTime'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectimages',
            options={'verbose_name_plural': 'Projects - Images'},
        ),
    ]
