# Generated by Django 4.2 on 2024-02-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0064_identityregister_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityregister',
            name='reference_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
