# Generated by Django 4.2 on 2024-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0066_identityregister_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Belum disemak', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Identity - Status',
                'ordering': ['status'],
            },
        ),
        migrations.RemoveField(
            model_name='identityregister',
            name='description',
        ),
        migrations.AddField(
            model_name='identityregister',
            name='statuses',
            field=models.ManyToManyField(to='kck2021.identitystatus'),
        ),
    ]
