# Generated by Django 4.2 on 2024-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0067_identitystatus_remove_identityregister_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityregister',
            options={'ordering': ['reference_code'], 'verbose_name_plural': 'Identity'},
        ),
        migrations.AlterField(
            model_name='identitystatus',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
