# Generated by Django 4.2 on 2024-02-18 03:15

from django.db import migrations, models
import django.db.models.deletion
import kck2021.models


class Migration(migrations.Migration):

    dependencies = [
        ('kck2021', '0069_identityregisterchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityregister',
            name='back',
            field=models.ImageField(upload_to=kck2021.models.back_image_upload_path),
        ),
        migrations.AlterField(
            model_name='identityregister',
            name='front',
            field=models.ImageField(upload_to=kck2021.models.front_image_upload_path),
        ),
        migrations.AlterField(
            model_name='identityregister',
            name='selfie',
            field=models.ImageField(upload_to=kck2021.models.selfie_image_upload_path),
        ),
        migrations.CreateModel(
            name='ReuploadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('identity_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kck2021.identityregister')),
            ],
        ),
    ]
